[platformio]
src_dir = .
default_envs = mks_tinybee_test

[env:mks_tinybee_test]
platform = espressif32@2.1.0
board = esp32dev
framework = arduino
monitor_speed = 38400
upload_speed = 921600
board_build.partitions = default_8MB.csv