#
# Marlin Firmware
# PlatformIO Configuration File
#

#################################
#                               #
#      ESP32 Architecture       #
#                               #
#################################

#
# Espressif ESP32
#
[env:esp32]
platform      = espressif32@2.1.0
board         = esp32dev
build_flags   = ${common.build_flags} -DCORE_DEBUG_LEVEL=0 -DCONFIG_BROWNOUT_DET_LVL=0 -DHALHOME="../../../../../Marlin/src"
src_filter    = ${common.default_src_filter} +<src/HAL/ESP32>
lib_ignore    = NativeEthernet, AsyncTCP_RP2040W
lib_deps      = kubafilinger/AsyncTCP@1.1.1
; upload_speed  = 500000
; monitor_speed = 250000
upload_speed = 921600
monitor_speed = 115200
#upload_port   = marlinesp.local
#board_build.flash_mode = qio

[env:FYSETC_E4]
platform               = espressif32@2.1.0
extends                = env:esp32
board_build.partitions = default_16MB.csv

[env:mks_tinybee]
extends                = env:esp32
platform               = espressif32@2.1.0
board_build.partitions = default_8MB.csv
; upload_port = COM9
build_flags   = ${env:esp32.build_flags}
src_filter    = ${common.default_src_filter} +<src/HAL/ESP32> +<src/lcd/menu> +<src/lcd/HD44780> +<src/lcd/utf8.cpp>